{
"date": "04_23",
"job_name": "pythia_largeRtrig",
"bkg_file": "data/largeR_trig/pythia_JZW.csv",
"web_path": "/project/projectdirs/atlas/www/multijet/RPV/btamadio/bkgEstimation/",
"is_mc": true,
"mc_label": "Pythia",
"n_toys": 100,
"inject_sig": false,
"sig_files": [],
"sig_mult": 0.0,
"sig_dsid": 0,
"template_type":0,
"bmatch_template":true,
"MJ_plots":["4jVRb9","4jVRb1","4jSRb9","4jSRb1",
            "5jVRb9","5jVRb1","5jSRb9","5jSRb1"],
"response_plots":["4js1VRb9bUe1","4js1VRb9bUe2","4js1VRb9bUe3","4js1VRb9bUe4",
                  "4js1VRb9bMe1","4js1VRb9bMe2","4js1VRb9bMe3","4js1VRb9bMe4"],
"blinded":false
}
